FROM python:3.11-slim

# Set system configurations
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install python modules
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy application sources
COPY backend /app/backend

EXPOSE 8000
EXPOSE 50051

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
